# Generated by Django 3.2.23 on 2023-12-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productsinput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Productname', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNumber', models.CharField(max_length=10)),
                ('Address', models.TextField()),
                ('PINCODE', models.IntegerField()),
                ('Image', models.ImageField(upload_to='pics')),
                ('Quantity_For_Sale', models.IntegerField()),
                ('Price_per_kg', models.IntegerField()),
                ('Comments', models.TextField()),
            ],
        ),
    ]
