# Generated by Django 3.2.23 on 2023-12-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_cartitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='image',
            field=models.ImageField(default='none', upload_to='pics'),
        ),
    ]
