# Generated by Django 3.2.23 on 2023-12-26 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_orderitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='price_at_purchase',
            new_name='unit_price_at_purchase',
        ),
    ]
