# Generated by Django 3.2.23 on 2023-12-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_orderdetails_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='Tracking_id',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
