# Generated by Django 3.2.23 on 2023-12-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='Image',
            field=models.ImageField(default='Nil', upload_to='reviewpic'),
        ),
    ]
